[phases.setup]
nixPkgs = ["nodejs", "php82", "php82Packages.composer", "bash"]

[phases.install]
cmds = [
  "npm install --prefix ./apis/hedera-api",
  "cd apis && composer install --no-dev --optimize-autoloader && cd ..",
  "chmod +x start.sh"
]

[start]
cmd = "bash start.sh"
